# TODO: Translation updated at 2024-08-15 10:49

translate spanish strings:

    # game/screens/scroll/hunt_events.rpy:2
    old "The event now known as the Fall of Beacon was a watershed moment for the world. It shattered alliances, convictions, assumptions and the very bedrock of civilization on Remnant. Never before had Hunters and students been so targeted, not even during the Great War: for all the conflicts and disputes in history, the unspoken rule had always been to respect the independence and life of Hunters. Their mission served the greater good and benefited everyone, no matter the nation or race."
    new "El evento ahora conociod como la Caída de Beacon fue como un tsunami para el mundo. Rompió alianzas, convicciones, asumpciones y los mismos cimientos de la civilización en Remnant. Nunca antes los Cazadores y estudiantes han sido tan marcados, ni siquiera incluso durante la Gran Guerra: para todos los conflictos y disputas en la historia, la regla no escirta ha sido siempre el respetar la independencia y vide de los Cazadores. Su misión sirve al bien mayor y benefica a todos, sin importar la nación o raza."

    # game/screens/scroll/hunt_events.rpy:3
    old "The White Fang shattered that rule: the attack used captive Grimm, they targeted civilians, Hunters and students alike, and if it weren't for the efforts of members of the latter group the Amity Arena would have fallen on Vale City, sending the number of casualities sky high. There are also rumours of a different nearby battle which, according to eyewitnesses, involved a Grimm the size of a literal mountain. The territory of Beacon Academy is now a no-man's zone overrun with Grimm, and the fallen Amity Arena is now a similarly grotesque relic."
    new "El White Fang rompió esa regla: el ataque usó Grimms captivos, ellos apuntaron a los civiles, Cazadores y estudiantes por igual, y si no fuera por los esfuerzos de los miembros del último grupo la Amity Arena habría caído en la Ciudad de Vale, enviando el número de casualidades por los cielos. Hay también rumores de una batalla diferente cerca que, de acuerdo a los testigos, involucraban a un Grimm del tamaño literal de una montaña. El territorio de la Academia Beacon es ahora una zona de ningun hombre repleta con Grimm, y la caída Arena Amity es ahora una reliquia grotescamente similar."

    # game/screens/scroll/hunt_events.rpy:4
    old "In the wake of the event, it was discovered that the White Fang didn't act alone: they had mysterious allies, even up to and including in the highest spheres of mistrali politics. The revelation landed Mistral in civil war as the trust between nations was broken, and so was the Network. It took Atlas an year to replace the connectivity lost with the transmission relay in the Tower of Beacon. In the process, the nation virtually overtook the running of the valesian chapter of the Hunters Organization and the capital of Vale, while its military gained significantly more influence internally."
    new "En el final del evento, se descubrió que el White Fang no actuó solo: tuvieron aliados misteriosos, incluso en las las esferas mas altas de las politicas mistralianas. La revelación sumió a Mistral en guerra civil ya que la confianza entre las naciones fue roto, y asi también la Red. Le tomó a Atlas un año para reemplzar la conectividad perdida con la repetidora de transmisión en la Torre de Beacon. En el proceso, la nación virtualmente tomó la sección valesiana de la Organización de Cazadores y la capital de Vale, mientras que su armada ganó significantemente mas influencia internamente."

    # game/screens/scroll/hunt_events.rpy:5
    old "Anti-faunus sentiments are at an all time high in Vale and Atlas both, and Menagerie has been forced to involve itself in international politics for the first time since its founding. Vacuo has similarly started taking a more pro-active stance in reaction to Atlas's increased international interventionism. Most surprising of all, though, was the development concerning the Beacon students and valesian Hunters who refused to be rolled into the new Atlas-ran structure. Taking possession of an once unclaimed piece of no-man's land in the Kingdom of Vale, they've founded a new nation, whose very existence is now already being called into question..."
    new "Los sentimientos Anti-Faunos siempre están altos en tanto Vale y Atlas, y Menagerie ha sido forzada a involverse a si misma en politicas internacionales por primera vez desde su fundación. Vacuo ha empezado similarmente a tomar una postura mas activa en reacción a la incrementada intervención internacional de Atlas. Lo mas sorprendente de todo, sin embargo, fue el desarrollo en lo que respecta a los estudiantes de Beacon y Cazadores valesinao que se negaron a unirse a la nueva estructura de Atlas. Tomando posesión de una parte de una tierra de nadie en el Reino de Vale, ellos fundaron una nueva nación, cuya mera existencia es ahora llamada a cuestionamiento..."

